apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-remove-kubeadmin
  namespace: rhacm-gitops-ns
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: mustonlyhave
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-remove-kubeadmin
      spec:
        remediationAction: enforce
        severity: low
        namespaceSelector:
          exclude:
            - kube-*
          include:
            - default
        object-templates:
          - complianceType: mustnothave
            objectDefinition:
              kind: Secret
              metadata:
                name: kubeadmin
                namespace: kube-system
              type: Opaque
