apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-monitoring-configmap
  namespace: openshift-gitops
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-monitoring-configmap
      spec:
        remediationAction: enforce
        severity: low
        namespaceSelector:
          exclude:
            - kube-*
          include:
            - default
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: cluster-monitoring-config
                namespace: openshift-monitoring
              data:
                config.yaml: |
                  enableUserWorkload: true
                  alertmanagerMain:
                    volumeClaimTemplate:
                      metadata:
                        name: alertmanager
                      spec:
                        resources:
                          requests:
                            storage: 10Gi
                  prometheusK8s:
                    retention: 24h
                    volumeClaimTemplate:
                      metadata:
                        name: prometheus
                      spec:
                        resources:
                          requests:
                            storage: 20Gi
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: user-workload-monitoring-config
                namespace: openshift-user-workload-monitoring
              data:
                config.yaml: |
                  prometheus:
                    retention: 24h
                    volumeClaimTemplate:
                      metadata:
                        name: prometheus
                      spec:
                        resources:
                          requests:
                            storage: 20Gi
