apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cluster-admin
  namespace: rhacm-gitops-ns
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-admin
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding 
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: cluster-admin-local
                subjects:
                - kind: User
                  name: superuser
                  apiGroup: rbac.authorization.k8s.io
                roleRef:
                  kind: ClusterRole 
                  name: cluster-admin
                  apiGroup: rbac.authorization.k8s.io
