apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: rhacm-manifests/base
    apps.open-cluster-management.io/reconcile-option: replace
  labels:
    app: all-clusters-policies
  name: all-clusters-policies-subscription-1
  namespace: openshift-gitops
spec:
  channel: rhacm-gitops-ns/github-rhacm-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: placementrule-infrastructure-policies
